### ISSUE TITLE
In ambient enum declarations member initializer must be constant expression.

### ISSUE THREAD

**Issue by DeepikaKochar** [triniwiz/nativescript-downloader#1]
### Make sure to check the demo app(s) for sample usage 
It's also giving error:
finished with reading lines with js files
C:\Users\deepikak\Downloads\nativescript-downloader-master\demo\platforms\android\build\intermediates\res\merged\F0F1\debug\values-v26\values-v26.xml:15:21-54: AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

C:\Users\deepikak\Downloads\nativescript-downloader-master\demo\platforms\android\build\intermediates\res\merged\F0F1\debug\values-v26\values-v26.xml:15: error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processF0F1DebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

When I add plugin It start to give below error:

Executing before-prepare hook from D:\Practise\Nativescript\App\App\hooks\before-prepare\nativescript-dev-typescript.js
Found peer TypeScript 2.2.2
node_modules/nativescript-downloader/downloader.common.d.ts(30,15): error TS1066: In ambient enum declarations member initializer must be constant expression.

node_modules/nativescript-downloader/downloader.common.d.ts(31,14): error TS1066: In ambient enum declarations member initializer must be constant expression.

node_modules/nativescript-downloader/downloader.common.d.ts(32,19): error TS1066: In ambient enum declarations member initializer must be constant expression.
node_modules/nativescript-downloader/downloader.common.d.ts(33,17): error TS1066: In ambient enum declarations member initializer must be constant expression.
node_modules/nativescript-downloader/downloader.common.d.ts(34,13): error TS1066: In ambient enum declarations member initializer must be constant expression.

Unable to apply changes on device: emulator-5554. Error is: TypeScript compiler failed with exit code 1.

### Which platform(s) does your issue occur on?
- Android/Not tested for iOS
- Android 7.0
- emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it): 
3.3.1

- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project):
 "version": "3.3.0"

- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project) : 
"tns-android": {
      "version": "3.3.1"
    }

- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)
"dependencies": {
    "@angular/animations": "~4.0.0",
    "@angular/common": "~4.0.0",
    "@angular/compiler": "~4.0.0",
    "@angular/core": "~4.0.0",
    "@angular/forms": "~4.0.0",
    "@angular/http": "~4.0.0",
    "@angular/platform-browser": "~4.0.0",
    "@angular/platform-browser-dynamic": "~4.0.0",
    "@angular/router": "~4.0.0",
    "base-64": "^0.1.0",
    "nativescript-angular": "~3.0.0",
    "nativescript-downloader": "^1.0.3",
    "nativescript-downloadmanager": "^0.1.0",
    "nativescript-drop-down": "^3.1.3",
    "nativescript-pdf-view": "^2.0.1",
    "nativescript-plugin-firebase": "^4.1.1",
    "nativescript-snackbar": "^1.1.7",
    "nativescript-social-login": "^1.8.2",
    "nativescript-social-share": "^1.4.0",
    "nativescript-sqlite": "^1.1.7",
    "nativescript-telerik-ui": "^3.1.4",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toast": "^1.4.6",
    "nativescript-webview-interface": "^1.4.1",
    "nativescript-xml2js": "^0.5.2",
    "nativescript-zip": "^1.3.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.2.0",
    "tns-core-modules": "^3.3.0",
    "zone.js": "0.8.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.0.0",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "^0.4.0",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.1.0",
    "typescript": "~2.2.1"
  },

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.

**Comment by triniwiz** [comment]
You will need the latest android build tools also if u are trying to build the demo u will need `"typescript": "~2.4.0"` because this plugin uses String enums which was introduced in `2.4.0`

**Comment by DeepikaKochar** [comment]
Thank you.. After upgrading I got it working. Great plugin..
