### ISSUE TITLE
Download Response from API

### ISSUE THREAD

**Issue by LorenDorez** [triniwiz/nativescript-downloader#11]
Can this plugin be used to download JSON data from an API?

I have a few API calls that return quite a bit of data and occasionally an Out Of Memory exception.

**Comment by triniwiz** [comment]
It should work

**Comment by LorenDorez** [comment]
Ill do a test project shortly to try it out. So would is just save the JSON response data from the API to an random file?

**Comment by triniwiz** [comment]
Yes or you can set the path and filename
