### ISSUE TITLE
Execution failed for task ':app:processF0F1F2F3F4F5F6F7DebugResources'.

### ISSUE THREAD

**Issue by LorenDorez** [triniwiz/nativescript-downloader#2]
F:\GLSS\Clients\Oversii\MobileApps\NativeScript\Patrolman Mobile App\platforms\android\app\build\intermediates\res\merged\F0F1F2F3F4F5F6F7\debug\values-v26\values-v26.xml:15:21-54: AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

F:\GLSS\Clients\Oversii\MobileApps\NativeScript\Patrolman Mobile App\platforms\android\app\build\intermediates\res\merged\F0F1F2F3F4F5F6F7\debug\values-v26\values-v26.xml:15: error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processF0F1F2F3F4F5F6F7DebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

**Comment by LorenDorez** [comment]
I have went into android studio and updated my  build tools to the latest version but still getting this error when i add the plugin

**Comment by triniwiz** [comment]
Try adding the following to your app.gradle located in the App_Resources the lib behind this plugin uses `27.0.2` from the support lib

```
configurations.all {
resolutionStrategy.eachDependency { DependencyResolveDetails details ->
    def requested = details.requested
    if (requested.group == 'com.android.support') {
        if (!requested.name.startsWith("multidex")) {
            details.useVersion '27.0.2'
        }
     }

   }
}
```

**Comment by LorenDorez** [comment]
Still getting the same build error

**Comment by LorenDorez** [comment]
I also tried running the command android update sdk and making sure the build tools are installed there as well

**Comment by triniwiz** [comment]
Add the following to the same file then rebuild

```
dependencies {
	compile 'com.android.support:appcompat-v7:27.0.02'
}
```

**Comment by LorenDorez** [comment]
Still no luck. Here is what my app.gradle looks like.

```
// Add your native dependencies here:

// Uncomment to add recyclerview-v7 dependency
//dependencies {
//	compile 'com.android.support:recyclerview-v7:+'
//}

android {  
  defaultConfig {  
    generatedDensities = []
    applicationId = "org.nativescript.PatrolmanMobileApp" 
    
    //override supported platforms
    // ndk {
    //       abiFilters.clear()
    //   		abiFilters "armeabi-v7a"
 		// }
  
  }  
  aaptOptions {  
    additionalParameters "--no-version-vectors"  
  }  
} 

def settingsGradlePath = "$rootDir/../../app/App_Resources/Android/settings.gradle";
def settingsGradleFile = new File(settingsGradlePath);
if(settingsGradleFile.exists())
{
    apply from: settingsGradleFile;
}

configurations.all {
resolutionStrategy.eachDependency { DependencyResolveDetails details ->
    def requested = details.requested
    if (requested.group == 'com.android.support') {
        if (!requested.name.startsWith("multidex")) {
            details.useVersion '27.0.2'
        }
     }

   }
}
dependencies {
	compile 'com.android.support:appcompat-v7:27.0.02'
}
```

**Comment by LorenDorez** [comment]
Its saying the SDK isnt install but i have installed it both from Android Studio and VS Code using android update sdk

**Comment by triniwiz** [comment]
verify the the sdk tools are updated 
<img width="756" alt="screen shot 2018-01-19 at 4 43 53 pm" src="https://user-images.githubusercontent.com/6695919/35170861-00c0d0fe-fd38-11e7-89cc-8efa2b31f1b4.png">

**Comment by LorenDorez** [comment]
I have in both areas. I am uninstalling and reinstalling right now

**Comment by LorenDorez** [comment]
When i run TNS doctor i get the following

You need to have the Android SDK Build-tools installed on your system. You can install any version in the following range: '>=23 <=26'.
Run $ %ANDROID_HOME%\tools\android from your command-line to install required Android Build Tools.

**Comment by LorenDorez** [comment]
Looks like uninstalling EVERYTHING and reinstall worked
