### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by nicHoch** [triniwiz/nativescript-downloader#22]
Hi i using the plugin to download large JSON data from an API endpoint. It is working well. But some endpoints are very computational intensive and I get a timeOut message before any data arrived.

is there a way how to configure the timeout for the *Time to first byte*?
  
### Which platform(s) does your issue occur on?
- Android device
- on iOS i do not see the timeout message

**Comment by triniwiz** [comment]
[IOS](https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking/AFURLRequestSerialization.h#L139) has a higher default timeout (60s) than [android](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/OkHttpClient.java#L496-L498) (10s) but I can add a prop to set a custom timeout

**Comment by nicHoch** [comment]
that would be awesome.

**Comment by triniwiz** [comment]
@nicHoch it's done 😄

**Comment by nicHoch** [comment]
@triniwiz Thaks for the update - very mush appreciated!
the extended default timeout on Android is working very well.
But if i use the static setTimeout method as shown in the readme 

```
	Downloader.init();
	Downloader.setTimeout(90);
```
i got following error: 

```
System.err: com.tns.NativeScriptException:
System.err: Calling js method run failed
System.err: TypeError: manager.setTimeout is not a function
System.err: File: "file:///data/data/com.thecrag.thecragapp/files/app/tns_modules/nativescript-downloader/downloader.js, line: 21, column: 16
System.err: StackTrace:
System.err:     Frame: function:'Downloader.setTimeout', file:'file:///data/data/com.thecrag.thecragapp/files/app/tns_modules/nativescript-downloader/downloader.js', line: 21, column: 17
System.err:     Frame: function:'', file:'file:///data/data/com.thecrag.thecragapp/files/app/pages/init/init.js', line: 138, column: 62
```

any ideas?


i already cleaned the platform/android and tempPlugin folder.

**Comment by triniwiz** [comment]
@nicHoch try nuking the platforms it should pull in the new lib the plugin uses 😄

**Comment by nicHoch** [comment]
@triniwiz hmmm i nuked everything but still the same error.

**Comment by alereisan** [comment]
@triniwiz I have the same error as @nicHoch when using Downloader.setTimeout() - nuked everything before

**Comment by triniwiz** [comment]
Can you try calling the after the app has started `app.on('launch',function(){ .Downloader.setTimeout()  })`

**Comment by alereisan** [comment]
@triniwiz It still shows Error (different app):
ERROR TypeError: manager.setTimeout is not a function

**Comment by MonasteryJohn** [comment]
I know this issue is closed, but using version 2.1.0 I am seeing the same behavior. It doesn't matter at what point in the app lifecycle it is called, the error "manager.SetTimeout is not a function" happens every way that I've tried it.

**Comment by rahadur** [comment]
I have the same problem. 😓
```
JS: ERROR Error: Uncaught (in promise): TypeError: manager.setTimeout is not a function
JS: TypeError: manager.setTimeout is not a function
JS:     at Function.Downloader.setTimeout (file:///data/data/app.xplatform.downloadmanager/files/app/tns_modules/nativescript-downloader/downloader.js:21:17)
JS:     at Object.<anonymous> (file:///data/data/app.xplatform.downloadmanager/files/app/app/home/home.component.js:7:38)
JS:     at require (<anonymous>:1:266)
JS:     at Object.<anonymous> (file:///data/data/app.xplatform.downloadmanager/files/app/app/home/home-routing.module.js:5:24)
JS:     at require (<anonymous>:1:266)
JS:     at Object.<anonymous> (file:///data/data/app.xplatform.downloadmanager/files/app/app/home/home.module.js:6:29)
JS:     at require (<anonymous>:1:266)
JS:     at file:///data/data/app.xplatform.downloadmanager/files/app/tns_modules/tns-core-modules/globals/globals.js:81:32
JS:     at new ZoneAwarePromise (file:///data/data/app.xplatform.downloadmanager/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:902:...
```

## Environment

```
√ Getting NativeScript components versions information...
‼ Update available for component nativescript. Your current version is 5.2.0 and the latest available version is 5.2.1.
√ Component tns-core-modules has 5.2.2 version and is up to date.
√ Component tns-android has 5.2.1 version and is up to date.
√ Component tns-ios has 5.2.0 version and is up to date.
```

**Comment by finger563** [comment]
also seeing the same issue

**Comment by tauanbinato** [comment]
Same here, TypeError: manager.setTimeout is not a function for android
