### ISSUE TITLE
Android build fails with DexArchiveMergerException

### ISSUE THREAD

**Issue by lini** [triniwiz/nativescript-downloader#23]
Using the current CLI version 4.2.0 I get the following errors in the console during gradle build:

    Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
    > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: ...

Steps to reproduce:

```bash
tns create testapp
cd testapp/
tns plugin add nativescript-downloader
tns build android
```

How to fix - the build is OK after I add `compile 'com.android.support:design:27.1.0'` in the include.gradle file of the plugin (in `platforms/andrdoid/include.gradle`):

```groovy
repositories {
    maven {
        url 'https://maven.google.com'
    }
}

dependencies {
    compile 'co.fitcom:fancydownloader:0.+'
    compile 'com.android.support:design:27.1.0'
}
```

**Comment by pasquiermichael** [comment]
Hi,
Thank you this solution works for me aswell, you can also put it directly in your project app.gradle (so you don't have to put it again everytime you remove/add android platform).
