### ISSUE TITLE
No headers on iOS

### ISSUE THREAD

**Issue by matecode** [triniwiz/nativescript-downloader#27]
With iOS Headers set in options are not recognized. If i look within the code they are just ignored? Any reasons for that?

**Comment by triniwiz** [comment]
I forgot

**Comment by prinzt** [comment]
Hi, thanks for all the good work!
Is this fixed already released? because i have installed "nativescript-downloader": "^2.1.4"
and the problem still exists. I also can't see the fix starting with "...if (options.headers)..." in downloader.ios.js

**Comment by matecode** [comment]
No unfortunately it isn't released yet, still open this bug
