### ISSUE TITLE
Download doesn't work on iOS since Nativescript 6.0

### ISSUE THREAD

**Issue by Beckmi2** [triniwiz/nativescript-downloader#38]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.
My problem occurs since migration to Nativescript 6.0. Before migration everything worked fine. Now Android works fine, but IOS doesn't. The Download on IOS won't start.

### Which platform(s) does your issue occur on?
- iOS

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it) 6.0.2

- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project) 6.0.4

- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
tns-android: 6.0.0
tns-ios: 6.0.1

- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)
"dependencies": {
        "@proplugins/nativescript-dom": "^2.1.0",
        "@proplugins/nativescript-globalevents": "^1.3.0",
        "@proplugins/nativescript-orientation": "^2.3.1",
        "@proplugins/nativescript-purchase": "^2.1.1",
        "fs-copy-file-sync": "1.1.1",
        "moment": "2.24.0",
        "nativescript-downloader": "2.1.4",
        "nativescript-local-notifications": "3.2.1",
        "nativescript-plugin-firebase": "9.0.2",
        "nativescript-sqlite": "latest",
        "nativescript-theme-core": "1.0.6",
        "nativescript-ui-listview": "7.0.0",
        "nativescript-ui-sidedrawer": "7.0.0",
        "rxjs": "6.5.2",
        "tns-core-modules": "~6.0.0"
    },
    "devDependencies": {
        "eslint": "5.16.0",
        "nativescript-dev-webpack": "~1.0.0",
        "node-sass": "4.12.0"
    },

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

I want to download an sqlite-database by touching a button on the first page and also on a second page. Both don't work on iOS since nativescript 6.0.

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.

I will provide a sample app. But it will take some time ...

**Comment by Beckmi2** [comment]
Here is the runnable project.
Menu 'Datenabgleich', button 'Download' should start the download.

[Downloader.zip](https://github.com/triniwiz/nativescript-downloader/files/3476971/Downloader.zip)

**Comment by Beckmi2** [comment]
@triniwiz can you please help?

**Comment by mennolp098** [comment]
@Beckmi2 I also cannot download on iOS I am getting a error (401) unauthorized.. Are you getting the same error message as me @Beckmi2?

**Comment by Beckmi2** [comment]
No, I don't get this error.
This is, what I get:

`CONSOLE LOG file:///app/home/home-page.js:202:0 Test:  Home
CONSOLE LOG file:///app/app-root/app-root.js:14:0 in onNavigationItemTap
CONSOLE LOG file:///app/app-root/app-root.js:21:0 componentRoute:  dbUpdate/dbUpdate-page
CONSOLE LOG file:///app/app-root/app-root.js:22:0 componentTitle:  dbUpdate
CONSOLE LOG file:///app/dbUpdate/dbUpdate-page.js:51:0 fileDownloaderId:  c15ec954-f9b4-eb2d-8298-91520f1ccfee
CONSOLE LOG file:///app/dbUpdate/dbUpdate-page.js:53:0 update-page.js - vor Abfrage, ob general.sqlite exisitert
CONSOLE LOG file:///app/dbUpdate/dbUpdate-page.js:77:0 row:  1,,1-1-0
CONSOLE LOG file:///app/dbUpdate/dbUpdate-page.js:88:0 last_DB_Update vor set:  03.03.19
CONSOLE LOG file:///app/dbUpdate/dbUpdate-page.js:90:0 last_DB_upadate aus der homeviewmodule.get:  03.03.19
CONSOLE LOG file:///app/dbUpdate/dbUpdate-page.js:100:0 in downloadFile
CONSOLE LOG file:///app/dbUpdate/dbUpdate-page.js:104:0 heute:  21.08.19
CONSOLE LOG file:///app/dbUpdate/dbUpdate-page.js:110:0 nach l\M-C\M-6schen der DB
CONSOLE LOG file:///app/dbUpdate/dbUpdate-page.js:121:0 fileDownloaderId:  c15ec954-f9b4-eb2d-8298-91520f1ccfee
Task <95D88A3A-5579-4E06-8BFD-D8475475DB0C>.<1> resuming, QOS(0x21)
Task <95D88A3A-5579-4E06-8BFD-D8475475DB0C>.<1> {strength 1, tls 8, ct 0, sub 0, sig 0, ciphers 1, bundle 0, builtin 0}
TIC Enabling TLS [6:0x28198fe40]
TIC TCP Conn Start [6:0x28198fe40]
[C6 Hostname#f7c25aac:443 tcp, url hash: b48f61b4, tls] start
nw_connection_report_state_with_handler_locked [C6] reporting state preparing
Task <95D88A3A-5579-4E06-8BFD-D8475475DB0C>.<1> setting up Connection 6
nw_endpoint_flow_protocol_connected [C6.1 IPv4#72abff49:443 in_progress channel-flow (satisfied)] Transport protocol connected
TIC TLS Event [6:0x28198fe40]: 1, Pending(0)
TIC TLS Event [6:0x28198fe40]: 11, Pending(0)
TIC TLS Event [6:0x28198fe40]: 14, Pending(0)
System Trust Evaluation yielded status(0)
TIC TLS Trust Result [6:0x28198fe40]: 0
TIC TLS Event [6:0x28198fe40]: 2, Pending(0)
nw_endpoint_flow_protocol_connected [C6.1 IPv4#72abff49:443 in_progress channel-flow (satisfied)] Output protocol connected
nw_connection_report_state_with_handler_locked [C6] reporting state ready
TIC TLS Event [6:0x28198fe40]: 20, Pending(0)
TIC TCP Conn Connected [6:0x28198fe40]: Err(16)
TIC TCP Conn Event [6:0x28198fe40]: 1
TIC TCP Conn Event [6:0x28198fe40]: 8
TIC TLS Handshake Complete [6:0x28198fe40]
new connection to <private> config 0x282ca8580
Task <95D88A3A-5579-4E06-8BFD-D8475475DB0C>.<1> now using Connection 6
nw_endpoint_flow_protocol_connected [C6.1 IPv4#72abff49:443 ready channel-flow (satisfied)] Output protocol connected
Task <95D88A3A-5579-4E06-8BFD-D8475475DB0C>.<1> sent request, body N
Task <95D88A3A-5579-4E06-8BFD-D8475475DB0C>.<1> received response, status 200 content K
Task <95D88A3A-5579-4E06-8BFD-D8475475DB0C>.<1> done using Connection 6
Task <95D88A3A-5579-4E06-8BFD-D8475475DB0C>.<1> response ended
TIC TCP Conn Event [6:0x28198fe40]: 1073741833
TIC TCP Conn Cancel [6:0x28198fe40]
[C6 Hostname#f7c25aac:443 tcp, url hash: b48f61b4, tls] cancel
[C6 Hostname#f7c25aac:443 tcp, url hash: b48f61b4, tls] cancelled
[C6.1 <private> 192.168.0.8:59193<->IPv4#72abff49:443]
Connected Path: satisfied (Path is satisfied), interface: en0, ipv4, ipv6, dns
Duration: 46.526s, DNS @0.000s took 1.566s, TCP @1.569s took 0.029s, TLS took 0.098s
bytes in/out: 455419/819, packets in/out: 332/10, rtt: 0.047s, retransmitted packets: 1, out-of-order packets: 0
0.000s [C6 <private> Hostname#f7c25aac:443 resolver] path:start
0.000s [C6 <private> Hostname#f7c25aac:443 resolver] path:satisfied
0.000s [C6 <private> Hostname#f7c25aac:443 resolver] resolver:start_dns
1.566s [C6 <private> Hostname#f7c25aac:443 resolver] resolver:receive_dns
1.566s [C6.1 <private> 192.168.0.8:59193<->IPv4#72abff49:443 channel-flow] path:start
1.567s [C6.1 <private> 192.168.0.8:59193<->IPv4#72abff49:443 channel-flow] path:satisfied
1.567s [C6.1 <private> 192.168.0.8:59193<->IPv4#72abff49:443 channel-flow] flow:start_nexus
1.568s [C6.1 <private> 192.168.0.8:59193<->IPv4#72abff49:443 channel-flow] flow:receive_nexus
1.569s [C6.1 <private> 192.168.0.8:59193<->IPv4#72abff49:443 channel-flow] flow:start_connect
1.598s [C6.1 <private> 192.168.0.8:59193<->IPv4#72abff49:443 channel-flow] flow:finish_transport
1.598s [C6 <private> Hostname#f7c25aac:443 resolver] flow:finish_transport
1.696s [C6.1 <private> 192.168.0.8:59193<->IPv4#72abff49:443 channel-flow] flow:finish_connect
1.696s [C6 <private> Hostname#f7c25aac:443 resolver] flow:finish_connect
1.696s [C6.1 <private> 192.168.0.8:59193<->IPv4#72abff49:443 channel-flow] flow:changed_viability
1.696s [C6 <private> Hostname#f7c25aac:443 resolver] flow:changed_viability
46.518s [C6.1 <private> 192.168.0.8:59193<->IPv4#72abff49:443 channel-flow] path:satisfied_change
46.518s [C6 <private> Hostname#f7c25aac:443 resolver] path:satisfied_change
46.519s [C6 <private> Hostname#f7c25aac:443 resolver] path:satisfied_change
46.526s [C6] path:cancel
nw_protocol_tcp_log_summary [C6.1:3]
[<private> <private>:59193<-><private>:443]
Init: 1, Conn_Time: 28.494ms, Syn's: 1, WR_T: 0/0, RD_T: 0/0, TFO: 0/0/0, ECN: 0/0/0, TS: 1
RTT_Cache: kernel, rtt_upd: 301, rtt: 47.437ms, rtt_var: 11.562ms rtt_nc: 47.437ms, rtt_var_nc: 11.562ms
nw_endpoint_flow_protocol_disconnected [C6.1 IPv4#72abff49:443 cancelled channel-flow (null)] Output protocol disconnected
nw_connection_report_state_with_handler_locked [C6] reporting state cancelled
TIC TCP Conn Destroyed [6:0x28198fe40]
nw_protocol_boringssl_get_output_frames(1301) <private>[0x102d7fe80] get output frames failed, state 8196
nw_protocol_boringssl_get_output_frames(1301) <private>[0x102d7fe80] get output frames failed, state 8196
success removing entry for host <private> config 0x282ca8580
TIC Read Status [6:0x0]: 1:57
TIC Read Status [6:0x0]: 1:57
`

**Comment by Beckmi2** [comment]
Update to version 2.1.5 solved my problem. 
Thanks for the update @triniwiz !
