### ISSUE TITLE
JS ERROR TypeError: null is not an object (evaluating 'owner.downloadsData') in downloader.js:60

### ISSUE THREAD

**Issue by AdamDenoon** [triniwiz/nativescript-downloader#4]
### Which platform(s) does your issue occur on?
- iOS 11.1
- iPhone 7 Simulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: tns 3.2.1
- Cross-platform modules: 3.3.0
- Runtime(s): 3.0.0

### Please, tell us how to recreate the issue in as much detail as possible. 
Use sample code provided

### Is there any code involved? 
    var downloader = new Downloader();
    var videoDownloaderId = downloader.createDownload({
        url:
          video_url,
        path:
          filePath
      });

      downloader
        .start(videoDownloaderId, progressData => {
          console.log(`Progress : ${progressData.value}%`);
        })
        .then(completed => {
          console.log(`Video : ${completed.path}`);
        })
        .catch(error => {
          console.log(error.message);
        });

**Comment by triniwiz** [comment]
Should be fixed in the latest version

**Comment by FranciZ** [comment]
@triniwiz I get this issue on iOS with version 1.1.0. It doesn't always happen so I'm guessing there's a race condition somewhere?

The error is:
`null is not an object (evaluating 'owner.downloadsData')`
