### ISSUE TITLE
Can Not invoke Fancy Downloader

### ISSUE THREAD

**Issue by LorenDorez** [triniwiz/nativescript-downloader#5]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
I get the following error
** ERROR => Error: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String co.fitcom.fancydownloader.ManagerService.create(co.fitcom.fancydownloader.Request)' on a null object reference

### Which platform(s) does your issue occur on?
Android

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it): 3.4.1

### Please, tell us how to recreate the issue in as much detail as possible. 
app.js
```
const downloadManager = require("nativescript-downloader").Downloader;
downloadManager.init();
```

test.js
```
const downloadManager = require("nativescript-downloader").Downloader;

test: function() {
try {
            const dm = new downloadManager();
            console.dir(dm);

            const did = dm.createDownload({
                url: "https://wallpaperscraft.com/image/hulk_wolverine_x_men_marvel_comics_art_99032_3840x2400.jpg"
            });
            //console.dir(dm);
        }
        catch (error) {
            console.log(`** Error => ${error}`);
        }
}
```

**Comment by hgc2002** [comment]
this is still happening on Android.
