### ISSUE TITLE
Nativescript 7 migrate!!

### ISSUE THREAD

**Issue by firumon** [triniwiz/nativescript-downloader#54]
After migrating to NS7, this plugin throws errors...

**Comment by triniwiz** [comment]
[Exhibit A](https://twitter.com/triniwiz/status/1307985570065461251?s=20) 😉

**Comment by ray007** [comment]
I suspect changing to `compilerOptions.target` in `tsconfig.json` to `"es6"` might already help.

**Comment by sfrcnayds** [comment]
@triniwiz any news on this plugin migration please ?

**Comment by Mc-Mido** [comment]
@triniwiz any news on this plugin migration please ?

**Comment by Mc-Mido** [comment]
@firumon @sfrcnayds FYI: 

https://github.com/triniwiz/nativescript-plugins/issues/15
https://twitter.com/triniwiz/status/1343501788851425281

> Next Youtube (almost ready), Downloader & WebRTC

**Comment by jeanpaulattard** [comment]
The following error is being thrown  `TypeError: Class constructor Observable cannot be invoked without 'new'` when I call `new Downloader()`. Is this one of the issues related to migration to NS7? Is there a workaround for it please?

Also what's the status update regarding this plugin please?

**Comment by sido420** [comment]
any updates on this? My app upgrade to NS 7 is blocked because of this plugin only. Are there other options?

**Comment by mdigas** [comment]
Change in file src/tsconfig.json:
    "target": "es5" to "target": "es6"
then use the pack.sh script to rebuild the package.
You can download the package from [here](https://drive.google.com/file/d/1OBRIIMVo-pXT1w_t-7iZFPYwhpk0IpQ6/view?usp=sharing)
Install the plugin from file (tns plugin add nativescript-downloader-2.1.5.tgz)
and error goes away!

**Comment by 7ammer** [comment]
Hi @mdigas,
Unfortunately I'm getting this error after downloading the package and running `plugin add nativescript-downloader-2.1.5.tgz`.
```
(CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Uncaught Error: -[NSInvocation getArgument:atIndex:]: NULL address argument
```

**Comment by mdigas** [comment]
> Hi @mdigas,
> Unfortunately I'm getting this error after downloading the package and running `plugin add nativescript-downloader-2.1.5.tgz`.
> 
> ```
> (CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Uncaught Error: -[NSInvocation getArgument:atIndex:]: NULL address argument
> ```

Hi 
I think that this error is in background-http:
https://github.com/NativeScript/nativescript-background-http/issues/270
and 3rror404 propose a fix in that post:
https://github.com/NativeScript/nativescript-background-http/issues/270#issuecomment-699504159

I think that is in ios platform. You can try 3rror404 workaround  but  you lose the ability to monitor progress with task.upload and task.totalUpload.

**Comment by ray007** [comment]
Apparently things are more complicated than just updating the `target` in `tsconfig.json`, otherwise I think (hope?) we'd already have gotten a new package.

**Comment by mdigas** [comment]
Searching the bug, i found that the problem is at downloader.ios.ts line:   291     invocation.getReturnValue(ret);

And for background-http has already fix it with this patch:
https://github.com/NativeScript/plugins/pull/16/files/4d28dfa34af72200aade9455bf5dd98505c7c73c

We must follow the above patch for nativescript-downloader

Btw for android platform the above plugin ([https://github.com/triniwiz/nativescript-downloader/issues/54#issuecomment-802071979](https://github.com/triniwiz/nativescript-downloader/issues/54#issuecomment-802071979)) works ok.

**Comment by mdigas** [comment]
I followed the guidlines of the above fix for background-http, compiled the nativescript-downloader plugin,
test it from [here](https://drive.google.com/file/d/1a1a7-jD8xixYI9FlAZDoWypOW55JlKHq/view?usp=sharing)
and let me know @7ammer....

**Comment by 7ammer** [comment]
That's amazing! Thanks @mdigas I'll take a look soon :)

**Comment by ray007** [comment]
Should this really be closed without a new release?

**Comment by triniwiz** [comment]
`@triniwiz/nativescript-downloader`

**Comment by ray007** [comment]
> 
> 
> `@triniwiz/nativescript-downloader`

Thank you. A link to the new source location from this repository would be nice I think...

**Comment by triniwiz** [comment]
Added to the readme @ray007
