### ISSUE TITLE
Multiple downloads

### ISSUE THREAD

**Issue by mspusta78** [triniwiz/nativescript-downloader#8]
on Android I can download 1 file without any issues, but then trying to download another file does not invoke the .start method

All I get is a new fileDownloadedId but then trying to call 
  downloader
          .start(fileDownloaderId, function(progressData) {
            console.log("Progress : " + progressData.value + "%");      
          })

never actually fires. I checked the status of the ID and getStatus of id=pending

any ideas? or suggestions?

**Comment by mspusta78** [comment]
I think I found an answer. It looks like that you can create only 1 downloader 
var DownloaderModule = require("nativescript-downloader");
var downloader = new DownloaderModule.Downloader();

and then use that downloader for all of the downloads.

I was calling 
var downloader = new DownloaderModule.Downloader();
for every new download

**Comment by nikoTM** [comment]
@mspusta78 how do you track progress for individual files then
